version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  auth_service:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env